# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/8BitCPU/8BitCPU.cache/wt [current_project]
set_property parent.project_path F:/8BitCPU/8BitCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/8BitCPU/8BitCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  F:/8BitCPU/8BitCPU.srcs/sources_1/new/Reg.v
  F:/8BitCPU/8BitCPU.srcs/sources_1/new/PC.v
  F:/8BitCPU/8BitCPU.srcs/sources_1/new/OrderStore.v
  F:/8BitCPU/8BitCPU.srcs/sources_1/new/DataStore.v
  F:/8BitCPU/8BitCPU.srcs/sources_1/new/Control.v
  F:/8BitCPU/8BitCPU.srcs/sources_1/new/ALU.v
}
set_property file_type "Verilog Header" [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/Reg.v]
set_property is_global_include true [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/Reg.v]
set_property file_type "Verilog Header" [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/PC.v]
set_property is_global_include true [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/PC.v]
set_property file_type "Verilog Header" [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/OrderStore.v]
set_property is_global_include true [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/OrderStore.v]
set_property file_type "Verilog Header" [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/DataStore.v]
set_property is_global_include true [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/DataStore.v]
set_property file_type "Verilog Header" [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/Control.v]
set_property is_global_include true [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/Control.v]
set_property file_type "Verilog Header" [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/ALU.v]
set_property is_global_include true [get_files F:/8BitCPU/8BitCPU.srcs/sources_1/new/ALU.v]
read_verilog -library xil_defaultlib {
  F:/8BitCPU/8BitCPU.srcs/sources_1/new/CLKControlAno.v
  F:/8BitCPU/8BitCPU.srcs/sources_1/new/ALUControl.v
  F:/8BitCPU/8BitCPU.srcs/sources_1/new/ControlRouteRemake.v
  F:/8BitCPU/8BitCPU.srcs/sources_1/new/TopOut.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/8BitCPU/8BitCPU.srcs/constrs_1/new/topcx.xdc
set_property used_in_implementation false [get_files F:/8BitCPU/8BitCPU.srcs/constrs_1/new/topcx.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TopOut -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TopOut.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TopOut_utilization_synth.rpt -pb TopOut_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
